name: Fly
main: TStark\Fly\Main
version: 1.0.0
api: 5.0.0
author: §bT. Stark
description: §6Fly command mode.
website: §ahttps://mcpetools.surge.sh

commands:
  fly:
    description: "Flight Command"
    usage: "/fly <on|off>"
    permission: "fly.command"

permissions:
  fly.command:
    description: "Fly mode"
    default: true
